[package]
name = "armstrong"
version = "0.1.0"
edition = "2025"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "armstrong"

[dependencies]
actix-web = "4"
tokio = { version = "1", features = ["macros", "rt-multi-thread"]}

[dev-dependencies]
reqwest = "0.11"

[target.aarch64-apple-darwin]
rustflags = ["-C", "link-arg=-fuse-ld=/opt/homebrew/opt/llvm/bin/ld64.lld"]